; PlatformIO Project Configuration File

[env:adafruit_matrix_portal_m4]
platform = atmelsam
board = adafruit_matrix_portal_m4
framework = arduino
lib_deps =
    adafruit/Adafruit Protomatter@^1.6.5
    adafruit/Adafruit GFX Library@^1.11.11
    adafruit/Adafruit BusIO@^1.16.2